preprocess:
  input: data/raw/data.csv
  output: data/processed/data.csv

split:
  input: data/processed/data.csv
  reference: data/processed/reference.csv
  current: data/processed/current.csv
  test_size: 0.3
  random_state: 42

train:
  data: data/processed/reference.csv
  target: Outcome
  model: models/model.pkl
  random_state: 42
  n_estimators: 100
  max_depth: 5

monitor:
  reference_data: data/processed/reference.csv
  current_data: data/processed/current.csv
