preprocess:
  input: data/raw/data.csv
  reference_output: data/processed/reference.csv
  current_output: data/processed/current.csv

train:
  data: data/processed/reference.csv
  target: Outcome
  model: models/model.pkl
  random_state: 42
  n_estimators: 100
  max_depth: 5
